### ISSUE TITLE
Find Work page never loads

### ISSUE THREAD

**Issue by rhyolight** [district0x/ethlance#227] opened 2020-03-03 16:14 UTC
Hi, I just created an account and went to "Find Work", but no matter what filters I enter (or with no filters at all) the page never loads. Url is https://ethlance.com/#/find/work?cat=1&o=0 and the page looks like this:

<img width="1792" alt="Screen Shot 2020-03-03 at 8 13 49 AM" src="https://user-images.githubusercontent.com/15566/75795277-f3e17180-5d26-11ea-907e-73facfbce2e6.png">

The console emits a couple of objects:

```
{Qb: "list"
name: "load-ids"
za: "list/load-ids"
Td: -937849526
v: 2153775}
{Qb: "ethlance-search-jobs"
name: "search-jobs"
za: "ethlance-search-jobs/search-jobs"
Td: 304337736
v: 2153775105
O: 4096}
```

Then shows this error:

```
Error: project ID is required
    at Object.InvalidResponse (inpage.js:1)
    at inpage.js:1
    at r.onreadystatechange (inpage.js:1)
    at r.t.dispatchEvent (inpage.js:1)
    at r._setReadyState (inpage.js:1)
    at r._onHttpResponseEnd (inpage.js:1)
    at n.IncomingMessage.<anonymous> (inpage.js:1)
    at inpage.js:1
    at n.IncomingMessage.s.emit (inpage.js:1)
    at M (inpage.js:1)
```

**Comment by rhyolight** [comment] 2020-03-03 16:17
When I go to my profile page while logged in, I can see my profile, but if I load my profile at https://ethlance.com/#/freelancer/0xe53ab42ef1cc3da793de5fe281f564b1946357b6 in an incognito window, I see this message:

<img width="1792" alt="Screen Shot 2020-03-03 at 8 15 50 AM" src="https://user-images.githubusercontent.com/15566/75795499-40c54800-5d27-11ea-953e-8eed6cbbedce.png">

> Oops, looks like we have trouble connecting into the Ethereum blockchain

**Comment by superkruger** [comment] 2020-03-18 09:30
Duplicate of https://github.com/district0x/ethlance/issues/217
I'd fix this myself if I new their Infura project ID...
But it seems no-one is looking at these issues.

**Closed** 2020-07-13 15:32 UTC
Labels: bug
