### ISSUE TITLE
Employer can't see messages from Candidate

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#414] opened 2024-05-01 06:00 UTC
This is when candidate is logged in: 

![image](https://github.com/district0x/ethlance/assets/3857155/f71f8d84-fe6f-46ee-9f96-a2f70631829c)

This is when employer is logged in: 

![image](https://github.com/district0x/ethlance/assets/3857155/dcbfb4be-f29d-4e29-b0b3-153d8768cd8c)

Should be solved together with https://github.com/district0x/ethlance/issues/411

**Comment by madis** [comment] 2024-05-07 11:35
This was caused by SQL query case sensistive (`=`) comparison of user-id column (mixed case) and the user-id coming from MetaMask (lower case). Fixed by using case-insensitive equals (`ILIKE`)

**Closed** 2024-05-11 01:03 UTC
Labels: bug
