### ISSUE TITLE
Available funds not changed after adding funds

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#395] opened 2024-04-17 08:05 UTC
Into this job I tried adding 0.01 amount of funds several times, I confirmed approval transaction and then transfer transaction, it went through ok, but then Available Funds at the job detail page shows same amount of 0.01.   https://ethlance.qa.district0x.io/jobs/0xE68AAA7bbA98A81dB838d5188FAB46ECb55731F2

![image](https://github.com/district0x/ethlance/assets/3857155/837ebf29-866f-4be4-bcc7-b836965b752e)

**Comment by madis** [comment] 2024-04-22 13:36
This is a weird issue. Locally I've seen this happening sporadically - the syncer receives the even, dispatches it (log: `INFO: Dispatching event`) but the handler for the event `ethlance.server.syncer/handle-job-funds-change` doesn't get called (even though the handlers are registered).

I resolved it locally by removing the compilation intermediate artifacts (`server/.shadow-cljs/*`, `server/.cpcache/*`, `server/out/*`) and recompiled. This could be caused by some macro compilation output not being re-compiled (macros in CLJS get compiled in JVM and inlined, if the macro file didn't change, the old output is inlined) 
But in QA/production this shouldn't happen as the builds (compilation) is done in a new docker container, so a blank slate, and thus no old compilation artifacts would be there.

I'll ponder over how to make it this issue (and its causes) more visible and track it in case it happens again.

**Comment by madis** [comment] 2024-05-21 20:13
Another note before closing it due to it not appearing in QA or locally.
The note is in case the issue appears again, to give a point for starting investigation.

Most of the contract event handlers in syncer are wrapped by `safe-go` macro. This should mean that if there is an error during event handling, in the end, an exception should be thrown. I suspect it was but it went unnoticed in the logs and the process kept on running and consequently not processing these events, which caused the _Available funds_ never to be updated.

https://github.com/district0x/ethlance/blob/a36d73bd80a4382e9961e89c8390b4e5427a3bd9/server/src/ethlance/server/syncer.cljs#L386

**Closed by madis** 2024-05-21 20:13 UTC
Labels: bug
